### ISSUE TITLE
When rapidly pressing two keys, an extra key is output

### ISSUE THREAD

**Issue by Recolate** [jberclaz/modelh#4] opened 2024-05-04 04:14 UTC
Hi, thanks for this repo. It was extremely helpful in converting my Model M. 

At first, it seemed like everything was fine, but I noticed when I typed up words like, "whatsoever" it would output as "whatsoeverc"

Holding down the "v" key while rapidly tapping the "e" and "r" will output "verc" and the same goes for other keys that are held down on that row. For example, holding down "b" and rapidly tapping "t" and "y" will output "btyn"

I'm basically completely ignorant, but maybe something is incorrect with the columns/rows in the firmware? I am curious if this is just a me issue or if anyone else can reproduce it.

**Comment by Recolate** [comment] 2024-05-05 02:43
FWIW I did some digging and was able to fix this, at least on my end. I went around checking to see if there were any alternative deghosting algorithms within QMK to utilize, much like how there's options for debouncing and so on. 

I found this repo, which was made for Unicomp's Mini M, and which features an alternative deghosting algorithm specifically for the Mini M: https://github.com/purdeaandrei/vial-qmk-mini-m
After cloning the repo and defining this new deghosting algorithm in the Model H's "config.h" file. 

Now I have no more issues with extra keys being output. The above repo, however, is somewhat out of date.

**Comment by fmunozs** [comment] 2024-05-05 04:33
I think this is not related to the firmware, but to the fact that the model m is not NKRO, I suppose the "deghosting" algorithm reduces some of the issues you found, but other keys combinations will reproduce the same problem.

**Comment by Recolate** [comment] 2024-05-05 04:52
> I think this is not related to the firmware, but to the fact that the model m is not NKRO, I suppose the "deghosting" algorithm reduces some of the issues you found, but other keys combinations will reproduce the same problem.

Yes, the 2KRO is likely the culprit, but, at least for me, the problem was only reproduceable on the Model H controller, and not the original one. Therefore IBM probably had some deghosting / blocking going for their controller as well. QMK also has this behavior by default, but perhaps it just wasn't robust enough for membrane buckling springs. I really don't know.

**Comment by jberclaz** [comment] 2024-06-22 00:42
There's an issue in the current firmware, because the de-ghosting algorithm is not enabled. I've commited a fix to the qmk firmware. I'm going to push the fix to vial-qmk as soon as I have time and will publish an updated version of the firmware on my repo.

**Comment by jberclaz** [comment] 2024-07-04 18:14
New firmware released with de-ghosting enabled.

**Closed by jberclaz** 2024-07-04 18:14 UTC

**Comment by fmunozs** [comment] 2024-08-13 00:59
@jberclaz just wondering where is the issue, I compiled my own version of vial-qmk and never noticed a problem. Is there any PR to see the problem?

**Comment by jberclaz** [comment] 2025-02-20 16:22
> [@jberclaz](https://github.com/jberclaz) just wondering where is the issue, I compiled my own version of vial-qmk and never noticed a problem. Is there any PR to see the problem?

Sorry, didn't see this message earlier. Here is the PR: https://github.com/qmk/qmk_firmware/pull/23744/files

**Comment by fmunozs** [comment] 2025-02-20 18:00
No problem! It was just a qmk issue, right ? I am using qmk-vial and didnt notice any ghosting

**Comment by jberclaz** [comment] 2025-02-21 02:56
> No problem! It was just a qmk issue, right ? I am using qmk-vial and didnt notice any ghosting

No, it affected both firmwares. Here is the vial PR: https://github.com/vial-kb/vial-qmk/pull/753
The ghosting doesn't happen often.
